### PR TITLE
Update required major version of mongoid to 5

### PR DESCRIPTION
**Pull request by akarmes**
@thetron Mongoid 5.0.0 is released: https://rubygems.org/gems/mongoid/versions/5.0.0

Hope you will merge this PR and publish new version of mongoid-enum to rubygems soon.

### CODE REVIEW

**Comment by 90yukke** [comment]
ok, it's failing because of mongoid-rspec. Hope it will be updated to mongoid 5.0.0 soon: https://github.com/mongoid-rspec/mongoid-rspec/pull/158

**Comment by thetron** [comment]
Ping me again when the build is green and i'll merge it straight away :smile:

**Comment by 90yukke** [comment]
@thetron updated

1) Latest version of DatabaseCleaner doesn't work with mongoid 5, because they removed delete_all method. Anyway, I don't why specs need DatabaseCleaner at all. After each spec it did

```ruby
DatabaseCleaner.clean
# and then
Mongoid.purge!
```

it seems like double work. And since `DatabaseCleaner` doesn't work now, I decided to remove it at all and leave `Mongoid.purge!`.
2) I changed `mongoid.yml` because of this:

> NOTE: Mongoid::Config.sessions is deprecated; use clients instead. It will be removed on or after 2015-12-01.

3) Right now mongoid show verbose logs by default. And it breaks beautiful rspec output. So I set log level to "info", as it was in mongoid 4:

```ruby
Mongo::Logger.logger.level = ::Logger::INFO
```

4) Rodrigo Pinto just published new version of mongoid-rspec, so I bumped major version inside gemspec.

**Comment by 90yukke** [comment]
@thetron Could you say something about this PR? The built is green. I suppose you will merge it, bump mongoid-enum version and publish it to rubygems

**Comment by Kris-LIBIS** [comment]
I second a new release of the gem as I would like to use it again with my mongoid-5 app.

**Comment by yspro** [comment]
:+1:

**Comment by karol-zygmunt-blaszczyk** [comment]
:+1:

**Comment by madwire** [comment]
:+1:

**Comment by temirov** [comment]
:+1:

**Comment by ahmet** [comment]
:+1:

**Comment by ArmandPredicSis** [comment]
:+1:

**Comment by tg0** [comment]
:+1:

**Comment by mklnz** [comment]
👍

**Comment by gajewsky** [comment]
:+1:

**Comment by Kris-LIBIS** [comment]
@thetron Many thumbs up, but still no release. Could you at least give us an estimate. I have a gem to release and I need to know if I have to use a different solution or not.

**Comment by thetron** [comment]
Finally able to take a look at this. Thanks @90yukke merging!

**Comment by thetron** [comment]
Released 0.4.0 on rubygems.

**Comment by Kris-LIBIS** [comment]
Thanks Nicholas. I used simple_enum for now, but I'll revert back to your gem soon.

**Pull request merged**
